### ISSUE TITLE
Non affine transforms invalidate bounds

### ISSUE THREAD

**Issue by chriskmanx** [mkeeter/ao#34]
I understand this issue is documented, but we might nonetheless deem it a bug :)

**Comment by mkeeter** [comment]
Hi Chris,

I recently pushed a history-changing update to `master` that removes the REPL in favor of a more featureful GUI.  As a part of this change, I took out the code that does bounds checking, so I'm closing your set of bounds-related issues.  If you'd like to fix them, I'll accept a PR against the `ao-guile-repl` branch, but I'm looking into more robust ways of tracking bounds in the future!
