### ISSUE TITLE
Problem building

### ISSUE THREAD

**Issue by nickodell** [mkeeter/ao#39]
I'm getting this error while running `cmake -DGUILE_INCLUDE_DIR=/usr/include/guile/2.2/ ..`:

```
CMake Error at CMakeLists.txt:52 (add_executable):
  Cannot find source file:

    tst.cpp
```

tst.cpp is mentioned by CMakeLists.txt, so I think this file is supposed to be here?

**Comment by nickodell** [comment]
Never mind, the commit  544574b fixes this.

**Comment by mkeeter** [comment]
Yup, *mea culpa* – I accidentally left an uncommited debugging file in the `CMakeLists.txt`
