### ISSUE TITLE
Multi-line indent?

### ISSUE THREAD

**Issue by omgitsraven** [mkeeter/ao#47]
I don't know if this is an easy thing to add in whatever GUI system you're using, but is there any way there could be some shortcut to add one level of indentation to a multi-line selection?

**Comment by mkeeter** [comment]
I'm definitely going to do a pass over the editor at some point, so I'll add this to the list.

**Comment by mkeeter** [comment]
Tab and shift-tab should now do what you want!

**Comment by omgitsraven** [comment]
Fantastic!! :) Thank you so much.
