### ISSUE TITLE
Bounding box geometry goes haywire if the camera is inside of it

### ISSUE THREAD

**Issue by omgitsraven** [mkeeter/ao#54]
Try either turning up the bounding box values to something large, or using the zoom/scroll gesture to bring the camera inside of it; you'll wind up seeing an 'X' drawn across the background for some reason.

**Comment by omgitsraven** [comment]
This commit does fix the 'x' when zooming too close, but now it seems like the bounding box is permanently orthographic, even when the view is set to 'perspective' mode?

**Comment by mkeeter** [comment]
Well, I fixed the always-orthographic issue, but now we're back to having the cross show up.  I think that the perspective projection matrix isn't *quite* right.

**Comment by omgitsraven** [comment]
I haven't looked closely into this, but based on stuff I've dealt with in the past, I think the projection matrix is fine, it's just lacking a nearplane?

**Comment by omgitsraven** [comment]
There we go, looks fine now :) Thanks!
