### ISSUE TITLE
Build fails on aarch64

### ISSUE THREAD

**Issue by bavier** [mkeeter/ao#69]
Hello Ao,

When I try to build Ao "ao-guile-repl" branch on aarch64 the build fails in the efsw directory with an error from `inotify_nosys.h`, saying "Unsupported architecture!"

The following patch fixes this.  Please forward to the efsw devs.

```
--- ao/ui/vendor/efsw/src/efsw/inotify-nosys.h  2017-12-14 16:27:16.125871099 -0600
+++ ao/ui/vendor/efsw/src/efsw/inotify-nosys.h  2017-12-14 16:26:39.786022981 -0600
@@ -69,6 +69,11 @@
 # define __NR_inotify_add_watch (__NR_SYSCALL_BASE+317)
 # define __NR_inotify_rm_watch (__NR_SYSCALL_BASE+318)

+#elif defined (__aarch64__)
+# define __NR_inotify_init 1043
+# define __NR_inotify_add_watch 27
+# define __NR_inotify_rm_watch 28
+
 #elif defined (__frv__)
 # define __NR_inotify_init 291
 # define __NR_inotify_add_watch 292
```

**Comment by mkeeter** [comment]
Hi @bavier !

`efsw` is maintained [here](https://bitbucket.org/SpartanJ/efsw) and I'm sure they'd appreciate your patch.

I'm no longer maintaining the `ao-guile-repl` branch, but if you open up a PR with these changes, I'll merge it in.
