### ISSUE TITLE
Behaviour on saved fail attempt triggered by new load

### ISSUE THREAD

**Issue by omgitsraven** [mkeeter/ao#82]
I don't know whether this is something you would fix, or something Qt would fix, or something Apple would fix, but, let me mention something that just happened to me:

- launched Studio
- typed some things into the empty document
- double-clicked an .ao document in the Finder
- Studio prompted me to save before it loads the new document
- it defaulted to saving in "Macintosh HD", which isn't writeable, but I clicked save anyway because I wasn't paying attention
- Studio displayed the "unable to save" error
- it then opened the loaded document anyway, and I lost what I'd written

I had written barely anything, so it's not the end of the world, but it seems like something worth mentioning in case it happens to someone who had written more, someday.

So the obvious issue here is "a write failure doesn't cancel queued loads", but I'm curious about something else -- where does Studio get its default save location? At first I was tempted to blame Apple for defaulting to a non-writeable path, but I just checked and TextEdit defaults to the desktop, so maybe it's a default that Qt is imposing? Is there a way to override it, to something like `~/Documents`? (Or just to have it remember the last path something was saved to?)

The one other thought that comes to mind is -- how difficult would it be to just have Studio open new documents in new windows, instead of "opening over" the open document? Sometimes I want to copy something from one document to another (which I know I could do in any text editor, but of course Studio is the default association...) and sometimes I want to compare how things look in two different versions...

**Comment by mkeeter** [comment]
I fixed the obvious issue, so now a failed save operation cancels a pending load / new / open.  I also changed the default path for save / load / export to be either the working directory (if a file is loaded) or the home directory.

Opening docs in new windows is theoretically possible, but would require a bit of reshuffling between the `App` and `Window` class, so I'll leave that for another time.
